from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

from deno import find_deno_bin

REPO_ROOT = Path(__file__).resolve().parents[1]
BROWSER_ENTRY = REPO_ROOT / "src/browser/index.ts"
EXTENSION_DIR = REPO_ROOT / "_extensions/marimo"
DIST_DIR = REPO_ROOT / "dist"
ASSETS_DIR = EXTENSION_DIR / "assets"
BRIDGE_CSS_SOURCE = json.loads((REPO_ROOT / "deno.json").read_text(encoding="utf-8"))[
    "imports"
]["@marimo-team/mdx-marimo/styles.css"]
NPM_CACHE_MODULE_RE = re.compile(
    r"(?P<prefix>(?:// |[\"']))[^\n\"']*npm/registry\.npmjs\.org/"
    r"(?P<package>(?:@[^/]+/)?[^/]+)/(?P<version>[^/]+)/(?P<path>[^\"'\n]+)"
)
BANNER = (
    "// Generated by `make browser-build` from src/browser and the mdx-marimo bridge.\n"
    "// Do not edit this file directly.\n"
)


def bundle(source: str | Path, *options: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            find_deno_bin(),
            "bundle",
            "--quiet",
            *options,
            str(source),
        ],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


def normalize_bundle(source: str) -> str:
    def replace(match: re.Match[str]) -> str:
        return (
            f"{match.group('prefix')}npm:{match.group('package')}"
            f"@{match.group('version')}/{match.group('path')}"
        )

    return NPM_CACHE_MODULE_RE.sub(replace, source)


def extension_version() -> str:
    config = (EXTENSION_DIR / "_extension.yml").read_text(encoding="utf-8")
    match = re.search(r'^version:\s*["\']?([^"\'\s#]+)["\']?\s*$', config, re.MULTILINE)
    if match is None:
        raise ValueError("marimo extension version is missing")
    return match.group(1)


def main() -> int:
    version = extension_version()
    javascript = bundle(
        BROWSER_ENTRY,
        "--platform",
        "browser",
        "--format",
        "esm",
    )
    if javascript.returncode != 0:
        sys.stderr.write(javascript.stderr)
        return javascript.returncode

    styles = bundle(BRIDGE_CSS_SOURCE, "--minify")
    if styles.returncode != 0:
        sys.stderr.write(styles.stderr)
        return styles.returncode

    DIST_DIR.mkdir(exist_ok=True)
    ASSETS_DIR.mkdir(exist_ok=True)
    browser_output = DIST_DIR / f"browser-v{version}.js"
    styles_output = DIST_DIR / f"islands-bridge-v{version}.css"
    browser_output.write_text(
        f"{BANNER}{normalize_bundle(javascript.stdout)}",
        encoding="utf-8",
    )
    styles_output.write_text(styles.stdout, encoding="utf-8")
    shutil.copyfile(browser_output, ASSETS_DIR / browser_output.name)
    shutil.copyfile(styles_output, ASSETS_DIR / styles_output.name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
