name: documentation
on:
  push:
    branches:
      - main

env:
  PIXI_VERSION: v0.67.0
  QUARTO_VERSION: 1.9.37

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b # v2
        with:
          version: ${{ env.QUARTO_VERSION }}

      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          pixi-version: ${{ env.PIXI_VERSION }}

      - name: Render
        run: pixi run ci

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@800bbc83122db9d4c38fcd284782d5afe62e52df # releases/v4
        with:
          branch: gh-pages
          folder: _site
